#!/bin/bash

warning ( ) {
    printf "\n${WARNING}$1${NC}\n------- \n"
}

info ( ) {
    printf "\n ---- \n\n${NC}\n${INFO}$1${NC}\n ---- \n"
}

success ( ) {
    printf "\n ---- \n\n${NC}\n${SUCCESS}$1${NC}\n---- \n"
}
