#!/bin/bash

warning ( ) {
    printf "\n${WARNING}$1${NC}\n------- \n"
}

info ( ) {
    printf "\n ---- \n\n${NC}$1\n${INFO}$2${NC}\n\n ---- \n"
}

success ( ) {
    printf "\n ---- \n\n${NC}$1\n${SUCCESS}$2${NC}\n\n ---- \n"
}
